libra/libra -> libra/diem

diff --git a/.github/workflows/test-move-prover.yml b/.github/workflows/test-move-prover.yml
--- a/.github/workflows/test-move-prover.yml
+++ b/.github/workflows/test-move-prover.yml
@@ -6,138 +6,131 @@ on:
 
 jobs:
   install_and_test_Move_Prover:
-
     runs-on: ubuntu-18.04
-    
+
     steps:
-    - name: Checkout libra
-      uses: actions/checkout@v2
-      with:
-        path: "libra"
-        fetch-depth: 50 # this is to make sure we obtain the target base commit
-        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
-        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
-    
-    - name: Detect the changes in move-prover
-      working-directory: ./libra
-      env:
-        BASE: ${{ github.event.client_payload.base_ref }}
-        PULL_ID: ${{ github.event.client_payload.pull_id }}
-      run: |
-        echo Test requested by https://github.com/libra/libra/pull/$PULL_ID
-        git diff --name-only $BASE
-        #if (git diff --name-only $BASE | grep "language/move-prover\|language/move-lang/src\|language/stdlib\|language/bytecode-verifier/src\|language/vm/src")
-        #if (git diff --name-only $BASE | grep "language/move-prover")
-        if false;
-        then
-          echo "::set-env name=RUN_TEST::yes"
-        else
-          echo "::set-env name=RUN_TEST::no"
-        fi
+      - name: Checkout libra
+        uses: actions/checkout@v2
+        with:
+          path: "libra"
+          fetch-depth: 50 # this is to make sure we obtain the target base commit
+          repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/diem
+          ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
 
-    - name: Install Z3
-      if: env.RUN_TEST == 'yes'
-      run: |
-        mkdir -p /home/runner/z3
-        cd /home/runner/z3
-        curl -LO https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/z3-4.8.9-x64-ubuntu-16.04.zip
-        unzip -j *
-        pwd
-        ls
-        ./z3 --version
-    
-    - name: Install .NET Core SDK and Boogie
-      if: env.RUN_TEST == 'yes'
-      run: |
-        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
-        sudo dpkg -i packages-microsoft-prod.deb
-        sudo apt-get update
-        sudo apt-get install apt-transport-https
-        sudo apt-get update
-        sudo apt-get install dotnet-sdk-3.1
-        dotnet tool install --global Boogie --version 2.7.30
-    
-    - name: Export the environment variables
-      if: env.RUN_TEST == 'yes'
-      run: |
-        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
-        echo "::set-env name=Z3_EXE::/home/runner/z3/z3"
-        echo "::set-env name=JOB_INS_ID::`curl -s https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID | egrep '/[0-9]{9}\?' -o | egrep '[0-9]{9}' -o`"
-    
-    - name: Test move-prover
-      if: env.RUN_TEST == 'yes'
-      id: test_move_prover
-      working-directory: ./libra/language/move-prover
-      timeout-minutes: 30 # normally, expected to be done within 10 mins.
-      run: |
-        set -o pipefail
-        if (cargo test --release 2>&1 | tee cargo_test.log)
-        then
-          echo "::set-env name=TEST_RESULT::pass"
-          exit 0
-        else
-          err=$?
-          echo "::set-env name=TEST_RESULT::fail"
-          exit $err
-        fi
+      - name: Detect the changes in move-prover
+        working-directory: ./libra
+        env:
+          BASE: ${{ github.event.client_payload.base_ref }}
+          PULL_ID: ${{ github.event.client_payload.pull_id }}
+        run: |
+          echo Test requested by https://github.com/libra/diem/pull/$PULL_ID
+          git diff --name-only $BASE
+          #if (git diff --name-only $BASE | grep "language/move-prover\|language/move-lang/src\|language/stdlib\|language/bytecode-verifier/src\|language/vm/src")
+          #if (git diff --name-only $BASE | grep "language/move-prover")
+          if false;
+          then
+            echo "::set-env name=RUN_TEST::yes"
+          else
+            echo "::set-env name=RUN_TEST::no"
+          fi
 
-    - name: Post the error message as a comment
-      if: env.RUN_TEST == 'yes' && failure()
-      uses: actions/github-script@0.6.0
-      env:
-        PULL_ID: ${{ github.event.client_payload.pull_id }}
-        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
-      with:
-        github-token: ${{secrets.MIRAI_BOT}}
-        script: |
-          test_result = (process.env.TEST_RESULT == undefined) ? 'timeout (> 30 mins)' : process.env.TEST_RESULT;
-          console.log(`Test ${test_result} occured on https://github.com/libra/libra/pull/${process.env.PULL_ID}`);
-          
-          if (process.env.JOB_INS_ID.length == 9) {
-            link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/runs/${process.env.JOB_INS_ID}?check_suite_focus=true#step:7:1`;
-          }
-          else {
-            link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`; 
-          }
-          msg = "".concat(
-            '[move-prover] Move Prover test (`language/move-prover/cargo test`) ',
-            `on commit [${process.env.ref.substring(0,7)}](https://github.com/libra/libra/commit/${process.env.ref}) `,
-            `did **${test_result}**. See [details](`,
-            link_to_log,
-            ').'
-          );
+      - name: Install Z3
+        if: env.RUN_TEST == 'yes'
+        run: |
+          mkdir -p /home/runner/z3
+          cd /home/runner/z3
+          curl -LO https://github.com/Z3Prover/z3/releases/download/z3-4.8.9/z3-4.8.9-x64-ubuntu-16.04.zip
+          unzip -j *
+          pwd
+          ls
+          ./z3 --version
 
-          console.log(msg);
-          github.issues.createComment({
-              owner: "libra",
-              repo: "libra",
-              issue_number: process.env.PULL_ID,
-              body: msg
-            });
+      - name: Install .NET Core SDK and Boogie
+        if: env.RUN_TEST == 'yes'
+        run: |
+          wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
+          sudo dpkg -i packages-microsoft-prod.deb
+          sudo apt-get update
+          sudo apt-get install apt-transport-https
+          sudo apt-get update
+          sudo apt-get install dotnet-sdk-3.1
+          dotnet tool install --global Boogie --version 2.7.30
 
+      - name: Export the environment variables
+        if: env.RUN_TEST == 'yes'
+        run: |
+          echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
+          echo "::set-env name=Z3_EXE::/home/runner/z3/z3"
+          echo "::set-env name=JOB_INS_ID::`curl -s https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID | egrep '/[0-9]{9}\?' -o | egrep '[0-9]{9}' -o`"
 
-        # const fs = require('fs');
-        # fs.readFile('libra/language/move-prover/cargo_test.log', 'utf-8', async (err, data) => {
-        #   if (err) {
-        #     console.log("err:", err);
-        #     console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
-        #     throw "No changes under `language/move-prover` were found.";
-        #     return;
-        #   }
-        #   if (!data) {
-        #     return;
-        #   }
+      - name: Test move-prover
+        if: env.RUN_TEST == 'yes'
+        id: test_move_prover
+        working-directory: ./libra/language/move-prover
+        timeout-minutes: 30 # normally, expected to be done within 10 mins.
+        run: |
+          set -o pipefail
+          if (cargo test --release 2>&1 | tee cargo_test.log)
+          then
+            echo "::set-env name=TEST_RESULT::pass"
+            exit 0
+          else
+            err=$?
+            echo "::set-env name=TEST_RESULT::fail"
+            exit $err
+          fi
 
-        #   lines = data.split('\n');
-        #   data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
-        #   data = "[move-prover] `cargo test` for Move Prover (`language/move-prover/bytecode-to-boogie`) failed with the following error message: \n```\n" + data + "\n```";    
+      - name: Post the error message as a comment
+        if: env.RUN_TEST == 'yes' && failure()
+        uses: actions/github-script@0.6.0
+        env:
+          PULL_ID: ${{ github.event.client_payload.pull_id }}
+          ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
+        with:
+          github-token: ${{secrets.MIRAI_BOT}}
+          script: |
+            test_result = (process.env.TEST_RESULT == undefined) ? 'timeout (> 30 mins)' : process.env.TEST_RESULT;
+            console.log(`Test ${test_result} occured on https://github.com/libra/diem/pull/${process.env.PULL_ID}`);
 
-        #   console.log('Message to send: \n' + data);
+            if (process.env.JOB_INS_ID.length == 9) {
+              link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/runs/${process.env.JOB_INS_ID}?check_suite_focus=true#step:7:1`;
+            }
+            else {
+              link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`; 
+            }
+            msg = "".concat(
+              '[move-prover] Move Prover test (`language/move-prover/cargo test`) ',
+              `on commit [${process.env.ref.substring(0,7)}](https://github.com/libra/diem/commit/${process.env.ref}) `,
+              `did **${test_result}**. See [details](`,
+              link_to_log,
+              ').'
+            );
 
-        #   console.log(process.env.COMMENTING);
-        #   console.log(env.BOOGIE_EXE);
-        #   console.log(env.Z3_EXE);
-
-        #   console.log(`https://github.com/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`);
-        #   throw "Move Prover test failed.";
-        # })
+            console.log(msg);
+            github.issues.createComment({
+                owner: "libra",
+                repo: "libra",
+                issue_number: process.env.PULL_ID,
+                body: msg
+              });
+          # const fs = require('fs');
+          # fs.readFile('libra/language/move-prover/cargo_test.log', 'utf-8', async (err, data) => {
+          #   if (err) {
+          #     console.log("err:", err);
+          #     console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
+          #     throw "No changes under `language/move-prover` were found.";
+          #     return;
+          #   }
+          #   if (!data) {
+          #     return;
+          #   }
+          #   lines = data.split('\n');
+          #   data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
+          #   data = "[move-prover] `cargo test` for Move Prover (`language/move-prover/bytecode-to-boogie`) failed with the following error message: \n```\n" + data + "\n```";
+          #   console.log('Message to send: \n' + data);
+          #   console.log(process.env.COMMENTING);
+          #   console.log(env.BOOGIE_EXE);
+          #   console.log(env.Z3_EXE);
+          #   console.log(`https://github.com/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`);
+          #   throw "Move Prover test failed.";
+          # })
