Update test-move-prover.yml

diff --git a/.github/workflows/test-move-prover.yml b/.github/workflows/test-move-prover.yml
--- a/.github/workflows/test-move-prover.yml
+++ b/.github/workflows/test-move-prover.yml
@@ -8,58 +8,36 @@ jobs:
   install_and_test_Move_Prover:
 
     runs-on: ubuntu-18.04
-  
+    
     steps:
-    - name: Dump GitHub context
-      env:
-        GITHUB_CONTEXT: ${{ toJson(github) }}
-      run: echo "$GITHUB_CONTEXT"
-    - name: Dump job context
-      env:
-        JOB_CONTEXT: ${{ toJson(job) }}
-      run: echo "$JOB_CONTEXT"
-    - name: Dump steps context
-      env:
-        STEPS_CONTEXT: ${{ toJson(steps) }}
-      run: echo "$STEPS_CONTEXT"
-    - name: Dump runner context
-      env:
-        RUNNER_CONTEXT: ${{ toJson(runner) }}
-      run: echo "$RUNNER_CONTEXT"
-    - name: Dump strategy context
-      env:
-        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
-      run: echo "$STRATEGY_CONTEXT"
-    - name: Dump matrix context
-      env:
-        MATRIX_CONTEXT: ${{ toJson(matrix) }}
-      run: echo "$MATRIX_CONTEXT"
-
     - name: Checkout libra
-      env:
-        HELLO: WORLD
-        HI: ${{ 'THERE' }}
       uses: actions/checkout@v2
       with:
         path: "libra"
         repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
         ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
+    
     - name: Detect the changes in move-prover
       working-directory: ./libra
       env:
         BASE: ${{ github.event.client_payload.base_ref }}
-        REF: ${{ env.HELLO }}
       run: |
-        echo $HELLO
-        echo $REF
-        echo $HI
         git diff --name-only $BASE
-        git diff --name-only $BASE | grep "language/move-prover"
+        if (git diff --name-only $BASE | grep "language/move-prover")
+        then
+          echo "::set-env name=RUN_TEST::yes"
+        else
+          echo "::set-env name=RUN_TEST::no"
+        fi
+    
     - name: Install Z3
+      if: env.RUN_TEST == 'yes'
       uses: pavpanchekha/setup-z3@v1.2
       with:
         version: "4.8.7"
+    
     - name: Install .NET Core SDK and Boogie
+      if: env.RUN_TEST == 'yes'
       run: |
         wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
         sudo dpkg -i packages-microsoft-prod.deb
@@ -68,63 +46,85 @@ jobs:
         sudo apt-get update
         sudo apt-get install dotnet-sdk-3.1
         dotnet tool install --global Boogie --version 2.5.7
+    
     - name: Export the environment variables
+      if: env.RUN_TEST == 'yes'
       run: |
         echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
         echo "::set-env name=Z3_EXE::`which z3`"
+    
     - name: Test move-prover
+      if: env.RUN_TEST == 'yes'
       id: test_move_prover
       working-directory: ./libra/language/move-prover/bytecode-to-boogie
       timeout-minutes: 20 # normally, expected to be done within 10 mins.
       run: |
+        echo "::set-env name=TEST_RESULT::timeout"
         set -o pipefail
-        cargo test 2>&1 | tee cargo_test.log
-    - name: Comment the error message if the test failed
-      if: failure()
-      uses: actions/github-script@0.5.0
+        if (cargo test 2>&1 | tee cargo_test.log)
+        then
+          echo "::set-env name=TEST_RESULT::pass"
+          exit 0
+        else
+          err=$?
+          echo "::set-env name=TEST_RESULT::fail"
+          exit $err
+        fi
+      
+      - name: Post the error message as a comment
+      if: env.RUN_TEST == 'yes' && failure()
+      uses: actions/github-script@0.6.0
       env:
         PULL_ID: ${{ github.event.client_payload.pull_id }}
-        COMMENTING: ${{ 'no' }}
       with:
         github-token: ${{secrets.MIRAI_BOT}}
+        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
         script: |
-          const fs = require('fs');
-          fs.readFile('libra/language/move-prover/bytecode-to-boogie/cargo_test.log', 'utf-8', async (err, data) => {
-            if (err) {
-              console.log("err:", err);
-              console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
-              throw "No changes under `language/move-prover` were found.";
-              return;
-            }
-            if (!data) {
-              return;
-            }
-            console.log("Move Prover test failed on https://github.com/libra/libra/pull/" + process.env.PULL_ID);
+          console.log(`Test ${process.env.TEST_RESULT} occured on https://github.com/libra/libra/pull/${process.env.PULL_ID}`);
+          console.log(`https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`);
+          console.log(`https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}?check_suite_focus=true#step:7:1`);
 
-            lines = data.split('\n');
-            data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
-            data = "[move-prover] `cargo test` for Move Prover (`language/move-prover/bytecode-to-boogie`) failed with the following error message: \n```\n" + data + "\n```";    
+          msg = '[move-prover] Move Prover test (`language/move-prover/bytecode-to-boogie/cargo test`) on commit [$(process.env.ref.substring(0,7))](https://github.com/libra/libra/commit/${process.env.ref}) ';
+          if (process.env.TEST_RESULT == 'timeout') {
+            msg = msg + 'timed out.';
+          }
+          if (process.env.TEST_RESULT == 'fail') {
+            msg = msg + 'failed.';
+          }
+          link = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}?check_suite_focus=true#step:7:1`;
+          msg = msg + `See [details](${link}).`;
 
-            console.log('Message to send: \n' + data);
+          console.log(msg);
 
-            console.log(process.env.COMMENTING);
-            console.log(env.BOOGIE_EXE);
-            console.log(env.Z3_EXE);
+        # github.issues.createComment({
+        #     owner: "libra",
+        #     repo: "libra",
+        #     issue_number: process.env.PULL_ID,
+        #     body: data
+        #   });
 
-            console.log(`https://github.com/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`);
-            throw "Move Prover test failed.";
-          })
-
-
-
-        # GITHUB_WORKFLOW_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
-
-        # if(process.env.COMMENTING == 'yes') {
-        #   await github.issues.createComment({
-        #       owner: "libra",
-        #       repo: "libra",
-        #       issue_number: process.env.PULL_ID,
-        #       body: data
-        #     });
+        # const fs = require('fs');
+        # fs.readFile('libra/language/move-prover/bytecode-to-boogie/cargo_test.log', 'utf-8', async (err, data) => {
+        #   if (err) {
+        #     console.log("err:", err);
+        #     console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
+        #     throw "No changes under `language/move-prover` were found.";
+        #     return;
         #   }
-        # }
+        #   if (!data) {
+        #     return;
+        #   }
+
+        #   lines = data.split('\n');
+        #   data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
+        #   data = "[move-prover] `cargo test` for Move Prover (`language/move-prover/bytecode-to-boogie`) failed with the following error message: \n```\n" + data + "\n```";    
+
+        #   console.log('Message to send: \n' + data);
+
+        #   console.log(process.env.COMMENTING);
+        #   console.log(env.BOOGIE_EXE);
+        #   console.log(env.Z3_EXE);
+
+        #   console.log(`https://github.com/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`);
+        #   throw "Move Prover test failed.";
+        # })
